### ISSUE TITLE
Dropdown has multiple entries for Outlook

### ISSUE THREAD

**Issue by acgourley** [jasonsalzman/react-add-to-calendar#11]
Sorry for the somewhat lazy test here, but I noticed after the upgrade from 0.0.9 to 0.0.12 there are two entries for outlook. Tested on iphone simulator. Screenshot: 
<img width="295" alt="screenshot 2017-05-23 13 07 28" src="https://cloud.githubusercontent.com/assets/7680/26375224/ed35f07a-3fbc-11e7-88e1-60bae40b9273.png">

**Comment by jasonsalzman** [comment]
That is not a bug, it's a requested feature added through PR #9 

Outlook downloads ics file and the Outlook.com link takes you to their web service.

**Comment by jasonsalzman** [comment]
If you would prefer not to have Outlook.com link display in the dropdown, you can change the links displayed using the `listItems` prop. Documentation is [here](https://github.com/jasonsalzman/react-add-to-calendar/blob/master/docs/ReactAddToCalendar.md#listitems)

Let me know if you have other questions.
