### ISSUE TITLE
iPhone calendar not working in latest release

### ISSUE THREAD

**Issue by acgourley** [jasonsalzman/react-add-to-calendar#12]
Upgrading from 0.0.9 to 0.0.12 breaks iphone calendar for me. It just loads this page: 
<img width="117" alt="screenshot 2017-05-23 13 07 47" src="https://cloud.githubusercontent.com/assets/7680/26375278/22408bd6-3fbd-11e7-8ec5-dd474d275efc.png">

**Comment by jasonsalzman** [comment]
A fix for this will be in place later this evening. Thank you for bringing this to my attention

**Comment by jasonsalzman** [comment]
If you would prefer not to have Outlook.com link display in the dropdown, you can change the links displayed using the `listItems` prop. Documentation is [here](https://github.com/jasonsalzman/react-add-to-calendar/blob/master/docs/ReactAddToCalendar.md#listitems)

Let me know if you have other questions.

**Comment by acgourley** [comment]
Thanks for looking into that!

**Comment by jasonsalzman** [comment]
This is now resolved in 0.0.13 for any react version below 15.5 or in 0.1.3 for any react version above 15.5.
