### ISSUE TITLE
Remove moment dependency

### ISSUE THREAD

**Issue by nickhudkins** [jasonsalzman/react-add-to-calendar#5]
I know that if you're dealing with dates, you probably are going to be using moment so this may be super silly, but... perhaps others can "bring their own" date library by exposing a "calculateDuration" prop or something like that.

I'm going to be doing it for myself since I am using 'fecha' instead of moment, so in a bit you'll have a PR that you can reject or accept! (I'll make sure it works with moment still too)

**Comment by jasonsalzman** [comment]
So sorry for the delayed response. Did you ever push your PR? I never saw anything come through.

**Comment by nickhudkins** [comment]
Ah sorry about that! I have everything locally. I'll get it pushed
tomorrow!

**Comment by mienaikoe** [comment]
Did this PR ever get merged?

**Comment by scripter-co** [comment]
@nickhudkins and update?

**Comment by nickhudkins** [comment]
It certainly doesn't appear like it did. I am not actively using this project and am a bit too far removed at this point to move this forward :(
