### ISSUE TITLE
Latest Safari does not open the event

### ISSUE THREAD

**Issue by MatejBalantic** [jasonsalzman/react-add-to-calendar#8]
In the Safari 10.0.3 on the latest macOS hitting the Apple Calendar button downloads a file `Unknown` - without any extension. This file doesn't open Calendar, but Text Edit.

Changing/adding extension manually to `.ics` resolves the problem

**Comment by manuelitox** [comment]
I just had the same problem. 

This issue is because the [Download](http://caniuse.com/#search=download) attribute isn't supported yet for stable version of Safari. I tried with the `10.2` and it was fixed.

cc @MatejBalantic @jasonsalzman

**Comment by acgourley** [comment]
This is a problem for me as well - I was hoping this could support older browsers and mobile safari but currently it does not.
